# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ddea898fee76b87c555754d65830ce3c31448b3ece64d2fecfdc94393514421b50e6705149ec20fc83519a41374af769142b4d26b7e82621ae75d3922890d68

test:
  secret_key_base: db223034fde47f6d88a4d6f25359d5a7f27efdabd506918f28ac24c21331721f85873405da6afeb811210db048c16890edd90d98b786a2e21c8e8a415ade2847

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
